services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insatpulse_app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-insatpulse_db}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    command: >
      sh -c "mkdir -p /var/www/html/public/uploads/users/profile_img /var/www/html/public/uploads/users/cover_img
      && chown -R www-data:www-data /var/www/html/public/uploads
      && php-fpm"
    expose:
      - "9000"
    volumes:
      - app_uploads:/var/www/html/public/uploads
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: insatpulse_nginx
    environment:
      DOMAIN: ${DOMAIN:-example.com}
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_uploads:/var/www/html/public/uploads:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped


volumes:
  app_uploads:
  certbot_etc:
  certbot_www: